name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          # This project uses only built-in libraries.
          pip install --upgrade pip

      - name: Install xvfb for GUI testing
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Unit Tests with xvfb-run
        run: |
          # xvfb-run allows us to run GUI tests in a headless environment
          xvfb-run python -m unittest discover
